//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTechProjectUsingSchemaFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string eventName { get; set; }
        public Nullable<System.TimeSpan> at { get; set; }
        public string location { get; set; }
        public string with { get; set; }
        public string shortNote { get; set; }
        public string userId { get; set; }
        public string comment { get; set; }
    
        public virtual user user { get; set; }
    }
}
