//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTechProjectUsingSchemaFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactInfo
    {
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string companyname { get; set; }
        public string userId { get; set; }
    
        public virtual user user { get; set; }
    }
}
